//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DBMapsModel", "Camera_env", "Environment", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MapBuilder.Environment), "Camera", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MapBuilder.Camera), true)]
[assembly: EdmRelationshipAttribute("DBMapsModel", "Map_env", "Environment", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MapBuilder.Environment), "Map", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MapBuilder.Map), true)]
[assembly: EdmRelationshipAttribute("DBMapsModel", "Pos_Map", "Map", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MapBuilder.Map), "Position", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MapBuilder.Position), true)]

#endregion

namespace MapBuilder
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBMapsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DBMapsEntities object using the connection string found in the 'DBMapsEntities' section of the application configuration file.
        /// </summary>
        public DBMapsEntities() : base("name=DBMapsEntities", "DBMapsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBMapsEntities object.
        /// </summary>
        public DBMapsEntities(string connectionString) : base(connectionString, "DBMapsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBMapsEntities object.
        /// </summary>
        public DBMapsEntities(EntityConnection connection) : base(connection, "DBMapsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Camera> Cameras
        {
            get
            {
                if ((_Cameras == null))
                {
                    _Cameras = base.CreateObjectSet<Camera>("Cameras");
                }
                return _Cameras;
            }
        }
        private ObjectSet<Camera> _Cameras;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Environment> Environments
        {
            get
            {
                if ((_Environments == null))
                {
                    _Environments = base.CreateObjectSet<Environment>("Environments");
                }
                return _Environments;
            }
        }
        private ObjectSet<Environment> _Environments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Map> Maps
        {
            get
            {
                if ((_Maps == null))
                {
                    _Maps = base.CreateObjectSet<Map>("Maps");
                }
                return _Maps;
            }
        }
        private ObjectSet<Map> _Maps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Position> Positions
        {
            get
            {
                if ((_Positions == null))
                {
                    _Positions = base.CreateObjectSet<Position>("Positions");
                }
                return _Positions;
            }
        }
        private ObjectSet<Position> _Positions;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cameras EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCameras(Camera camera)
        {
            base.AddObject("Cameras", camera);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Environments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEnvironments(Environment environment)
        {
            base.AddObject("Environments", environment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Maps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMaps(Map map)
        {
            base.AddObject("Maps", map);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Positions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPositions(Position position)
        {
            base.AddObject("Positions", position);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBMapsModel", Name="Camera")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Camera : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Camera object.
        /// </summary>
        /// <param name="iD_camera">Initial value of the ID_camera property.</param>
        public static Camera CreateCamera(global::System.Int32 iD_camera)
        {
            Camera camera = new Camera();
            camera.ID_camera = iD_camera;
            return camera;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Frame_rate
        {
            get
            {
                return _Frame_rate;
            }
            set
            {
                OnFrame_rateChanging(value);
                ReportPropertyChanging("Frame_rate");
                _Frame_rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Frame_rate");
                OnFrame_rateChanged();
            }
        }
        private Nullable<global::System.Int32> _Frame_rate;
        partial void OnFrame_rateChanging(Nullable<global::System.Int32> value);
        partial void OnFrame_rateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Resolution_video
        {
            get
            {
                return _Resolution_video;
            }
            set
            {
                OnResolution_videoChanging(value);
                ReportPropertyChanging("Resolution_video");
                _Resolution_video = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Resolution_video");
                OnResolution_videoChanged();
            }
        }
        private Nullable<global::System.Int32> _Resolution_video;
        partial void OnResolution_videoChanging(Nullable<global::System.Int32> value);
        partial void OnResolution_videoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Resolution_matrix
        {
            get
            {
                return _Resolution_matrix;
            }
            set
            {
                OnResolution_matrixChanging(value);
                ReportPropertyChanging("Resolution_matrix");
                _Resolution_matrix = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Resolution_matrix");
                OnResolution_matrixChanged();
            }
        }
        private Nullable<global::System.Int32> _Resolution_matrix;
        partial void OnResolution_matrixChanging(Nullable<global::System.Int32> value);
        partial void OnResolution_matrixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_environment
        {
            get
            {
                return _ID_environment;
            }
            set
            {
                OnID_environmentChanging(value);
                ReportPropertyChanging("ID_environment");
                _ID_environment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_environment");
                OnID_environmentChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_environment;
        partial void OnID_environmentChanging(Nullable<global::System.Int32> value);
        partial void OnID_environmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_camera
        {
            get
            {
                return _ID_camera;
            }
            set
            {
                if (_ID_camera != value)
                {
                    OnID_cameraChanging(value);
                    ReportPropertyChanging("ID_camera");
                    _ID_camera = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_camera");
                    OnID_cameraChanged();
                }
            }
        }
        private global::System.Int32 _ID_camera;
        partial void OnID_cameraChanging(global::System.Int32 value);
        partial void OnID_cameraChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBMapsModel", "Camera_env", "Environment")]
        public Environment Environment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Environment>("DBMapsModel.Camera_env", "Environment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Environment>("DBMapsModel.Camera_env", "Environment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Environment> EnvironmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Environment>("DBMapsModel.Camera_env", "Environment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Environment>("DBMapsModel.Camera_env", "Environment", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBMapsModel", Name="Environment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Environment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Environment object.
        /// </summary>
        /// <param name="iD_environment">Initial value of the ID_environment property.</param>
        public static Environment CreateEnvironment(global::System.Int32 iD_environment)
        {
            Environment environment = new Environment();
            environment.ID_environment = iD_environment;
            return environment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Illumination
        {
            get
            {
                return _Illumination;
            }
            set
            {
                OnIlluminationChanging(value);
                ReportPropertyChanging("Illumination");
                _Illumination = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Illumination");
                OnIlluminationChanged();
            }
        }
        private Nullable<global::System.Int32> _Illumination;
        partial void OnIlluminationChanging(Nullable<global::System.Int32> value);
        partial void OnIlluminationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Time;
        partial void OnTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Robots_width
        {
            get
            {
                return _Robots_width;
            }
            set
            {
                OnRobots_widthChanging(value);
                ReportPropertyChanging("Robots_width");
                _Robots_width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Robots_width");
                OnRobots_widthChanged();
            }
        }
        private Nullable<global::System.Int32> _Robots_width;
        partial void OnRobots_widthChanging(Nullable<global::System.Int32> value);
        partial void OnRobots_widthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_environment
        {
            get
            {
                return _ID_environment;
            }
            set
            {
                if (_ID_environment != value)
                {
                    OnID_environmentChanging(value);
                    ReportPropertyChanging("ID_environment");
                    _ID_environment = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_environment");
                    OnID_environmentChanged();
                }
            }
        }
        private global::System.Int32 _ID_environment;
        partial void OnID_environmentChanging(global::System.Int32 value);
        partial void OnID_environmentChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBMapsModel", "Camera_env", "Camera")]
        public EntityCollection<Camera> Cameras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Camera>("DBMapsModel.Camera_env", "Camera");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Camera>("DBMapsModel.Camera_env", "Camera", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBMapsModel", "Map_env", "Map")]
        public EntityCollection<Map> Maps
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Map>("DBMapsModel.Map_env", "Map");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Map>("DBMapsModel.Map_env", "Map", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBMapsModel", Name="Map")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Map : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Map object.
        /// </summary>
        /// <param name="iD_map">Initial value of the ID_map property.</param>
        public static Map CreateMap(global::System.Int32 iD_map)
        {
            Map map = new Map();
            map.ID_map = iD_map;
            return map;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Floor
        {
            get
            {
                return _Floor;
            }
            set
            {
                OnFloorChanging(value);
                ReportPropertyChanging("Floor");
                _Floor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Floor");
                OnFloorChanged();
            }
        }
        private Nullable<global::System.Int32> _Floor;
        partial void OnFloorChanging(Nullable<global::System.Int32> value);
        partial void OnFloorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Scale
        {
            get
            {
                return _Scale;
            }
            set
            {
                OnScaleChanging(value);
                ReportPropertyChanging("Scale");
                _Scale = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Scale");
                OnScaleChanged();
            }
        }
        private Nullable<global::System.Int32> _Scale;
        partial void OnScaleChanging(Nullable<global::System.Int32> value);
        partial void OnScaleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_environment
        {
            get
            {
                return _ID_environment;
            }
            set
            {
                OnID_environmentChanging(value);
                ReportPropertyChanging("ID_environment");
                _ID_environment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_environment");
                OnID_environmentChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_environment;
        partial void OnID_environmentChanging(Nullable<global::System.Int32> value);
        partial void OnID_environmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_map
        {
            get
            {
                return _ID_map;
            }
            set
            {
                if (_ID_map != value)
                {
                    OnID_mapChanging(value);
                    ReportPropertyChanging("ID_map");
                    _ID_map = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_map");
                    OnID_mapChanged();
                }
            }
        }
        private global::System.Int32 _ID_map;
        partial void OnID_mapChanging(global::System.Int32 value);
        partial void OnID_mapChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBMapsModel", "Map_env", "Environment")]
        public Environment Environment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Environment>("DBMapsModel.Map_env", "Environment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Environment>("DBMapsModel.Map_env", "Environment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Environment> EnvironmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Environment>("DBMapsModel.Map_env", "Environment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Environment>("DBMapsModel.Map_env", "Environment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBMapsModel", "Pos_Map", "Position")]
        public EntityCollection<Position> Positions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Position>("DBMapsModel.Pos_Map", "Position");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Position>("DBMapsModel.Pos_Map", "Position", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBMapsModel", Name="Position")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Position : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Position object.
        /// </summary>
        /// <param name="iD_position">Initial value of the ID_position property.</param>
        public static Position CreatePosition(global::System.Int32 iD_position)
        {
            Position position = new Position();
            position.ID_position = iD_position;
            return position;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CoordX
        {
            get
            {
                return _CoordX;
            }
            set
            {
                OnCoordXChanging(value);
                ReportPropertyChanging("CoordX");
                _CoordX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CoordX");
                OnCoordXChanged();
            }
        }
        private Nullable<global::System.Int32> _CoordX;
        partial void OnCoordXChanging(Nullable<global::System.Int32> value);
        partial void OnCoordXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CoordY
        {
            get
            {
                return _CoordY;
            }
            set
            {
                OnCoordYChanging(value);
                ReportPropertyChanging("CoordY");
                _CoordY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CoordY");
                OnCoordYChanged();
            }
        }
        private Nullable<global::System.Int32> _CoordY;
        partial void OnCoordYChanging(Nullable<global::System.Int32> value);
        partial void OnCoordYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Angle
        {
            get
            {
                return _Angle;
            }
            set
            {
                OnAngleChanging(value);
                ReportPropertyChanging("Angle");
                _Angle = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Angle");
                OnAngleChanged();
            }
        }
        private Nullable<global::System.Int32> _Angle;
        partial void OnAngleChanging(Nullable<global::System.Int32> value);
        partial void OnAngleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_map
        {
            get
            {
                return _ID_map;
            }
            set
            {
                OnID_mapChanging(value);
                ReportPropertyChanging("ID_map");
                _ID_map = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_map");
                OnID_mapChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_map;
        partial void OnID_mapChanging(Nullable<global::System.Int32> value);
        partial void OnID_mapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_position
        {
            get
            {
                return _ID_position;
            }
            set
            {
                if (_ID_position != value)
                {
                    OnID_positionChanging(value);
                    ReportPropertyChanging("ID_position");
                    _ID_position = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_position");
                    OnID_positionChanged();
                }
            }
        }
        private global::System.Int32 _ID_position;
        partial void OnID_positionChanging(global::System.Int32 value);
        partial void OnID_positionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBMapsModel", "Pos_Map", "Map")]
        public Map Map
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Map>("DBMapsModel.Pos_Map", "Map").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Map>("DBMapsModel.Pos_Map", "Map").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Map> MapReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Map>("DBMapsModel.Pos_Map", "Map");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Map>("DBMapsModel.Pos_Map", "Map", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
